name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12

    - name: Build
      run: go build -v ./...
      
    - uses: actions/upload-artifact@v2
      with:
       name: artnet-analyzer
       path: ./artnet-analyzer

    - name: Test
      run: go test -v ./...
