name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12

    - name: Build
      run: go build -v
      
    - uses: actions/upload-artifact@v2
      with:
       name: artnet-analyzer-linux
       path: ./artnet-analyzer

    - name: Test
      run: go test -v ./...

  build-on-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12

    - name: Build
      run: go build -v
      
    - uses: actions/upload-artifact@v2
      with:
       name: artnet-analyzer-win
       path: artnet-analyzer.exe

    - name: Test
      run: go test -v ./...
